<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="WINDOWS-UNR7VLH"><DocLocation><![CDATA[C:\Users\Administrator\Documents\Unified Functional Testing\day 2 lab 1]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[day 2 lab 1]]></DName>
<Res><![CDATA[Res3]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[15-03-2023 - 16:35:47]]></Time>
<TimeTick>1678878347</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "http://demo.opencart.com/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "http://demo.opencart.com/",1]]></Details>
<Time><![CDATA[15-03-2023 - 16:35:47]]></Time>
<TimeTick>1678878347</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Run "http://demo.opencart.com/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[15-03-2023 - 16:35:52]]></Time>
<TimeTick>1678878352</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA["Your Store"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (2 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Your Store<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>title=Your Store<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openurl=https://demo.opencart.com<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=Your Store<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[15-03-2023 - 16:35:52]]></Time>
<TimeTick>1678878352</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="14" Source="Action1" SourceLine="2" >
<Disp><![CDATA["Your Store"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-03-2023 - 16:35:52]]></Time>
<TimeTick>1678878352</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[My Account.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-03-2023 - 16:35:52]]></Time>
<TimeTick>1678878352</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="17" Source="Action1" SourceLine="2" >
<Disp><![CDATA[My Account.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Register.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-03-2023 - 16:35:53]]></Time>
<TimeTick>1678878353</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="20" Source="Action1" SourceLine="3" >
<Disp><![CDATA[Register.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="16" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Register Account]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-03-2023 - 16:35:55]]></Time>
<TimeTick>1678878355</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[firstname.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ab"]]></Details>
<Time><![CDATA[15-03-2023 - 16:35:55]]></Time>
<TimeTick>1678878355</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="24" Source="Action1" SourceLine="4" >
<Disp><![CDATA[firstname.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[lastname.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["c"]]></Details>
<Time><![CDATA[15-03-2023 - 16:35:56]]></Time>
<TimeTick>1678878356</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="27" Source="Action1" SourceLine="5" >
<Disp><![CDATA[lastname.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["abc@mail.com"]]></Details>
<Time><![CDATA[15-03-2023 - 16:35:56]]></Time>
<TimeTick>1678878356</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="30" Source="Action1" SourceLine="6" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["6411a45e6c76b1582cfdf67e4f9b"]]></Details>
<Time><![CDATA[15-03-2023 - 16:35:56]]></Time>
<TimeTick>1678878356</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="33" Source="Action1" SourceLine="7" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[agree.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[15-03-2023 - 16:35:57]]></Time>
<TimeTick>1678878357</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="36" Source="Action1" SourceLine="8" >
<Disp><![CDATA[agree.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Continue.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-03-2023 - 16:35:57]]></Time>
<TimeTick>1678878357</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="39" Source="Action1" SourceLine="9" >
<Disp><![CDATA[Continue.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[My Account.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-03-2023 - 16:35:57]]></Time>
<TimeTick>1678878357</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="42" Source="Action1" SourceLine="10" >
<Disp><![CDATA[My Account.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-03-2023 - 16:35:58]]></Time>
<TimeTick>1678878358</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="45" Source="Action1" SourceLine="11" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[email_2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["abc@mail.com"]]></Details>
<Time><![CDATA[15-03-2023 - 16:36:00]]></Time>
<TimeTick>1678878360</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="48" Source="Action1" SourceLine="12" >
<Disp><![CDATA[email_2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["6411a47bbdb688f2ec60cc3a4d03"]]></Details>
<Time><![CDATA[15-03-2023 - 16:36:00]]></Time>
<TimeTick>1678878360</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="51" Source="Action1" SourceLine="13" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-03-2023 - 16:36:00]]></Time>
<TimeTick>1678878360</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="54" Source="Action1" SourceLine="14" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Object&nbsp;is&nbsp;disabled]]></Details>
<Time><![CDATA[15-03-2023 - 16:36:01]]></Time>
<TimeTick>1678878361</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebButton<br>Html Tag = BUTTON<br>_xpath = //FORM[@id="form-login"]/BUTTON[normalize-space()="Login"]<br>|Visible = -1<br>Value = Login<br>Type = submit<br>Name = Login<br>Html Id = <br>DHTML Class = btn btn-primary<br>acc_name = <br>]]></Details>
<Time><![CDATA[15-03-2023 - 16:36:01]]></Time>
<TimeTick>1678878361</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="58" status="Warning" nType="Description" Source="Action1" SourceLine="15" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="12" nRep="57" status="Failed" nType="Run Error" Source="Action1" SourceLine="15" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="23" status="Failed" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Register Account]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="13" status="Failed" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[15-03-2023 - 16:36:01]]></Time>
<TimeTick>1678878361</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object is disabled<BR/>Line (16): &quot;Set obj=Browser(&quot;Your Store&quot;).Page(&quot;Register Account&quot;).WebButton(&quot;Login&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[15-03-2023 - 16:36:01]]></Time>
<TimeTick>1678878361</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="60" status="Failed" Source="Action1" SourceLine="15" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[15-03-2023 - 16:36:08]]></Time>
<TimeTick>1678878368</TimeTick>
<NodeArgs eType="General" icon="14" nRep="61" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="59" status="Failed" Source="Action1" SourceLine="15" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="15-03-2023 - 16:35:46" eTime="15-03-2023 - 16:36:08" passed="1" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[day 2 lab 1 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="15-03-2023 - 16:35:41" eTime="15-03-2023 - 16:36:08" passed="1" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test day 2 lab 1 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>