<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="WINDOWS-UNR7VLH"><DocLocation><![CDATA[C:\Users\Administrator\Documents\Unified Functional Testing\function test]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[function test]]></DName>
<Res><![CDATA[Res3]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:15]]></Time>
<TimeTick>1678784355</TimeTick>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:15]]></Time>
<TimeTick>1678784355</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="9" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="3" nRep="8" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:16]]></Time>
<TimeTick>1678784356</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["join"]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:16]]></Time>
<TimeTick>1678784356</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[s1]]></Obj>
<Details plainTxt="False" ><![CDATA[<SPAN class=text><div align=left><dl><b><u>Scenario</u>: </b>s1<br><b><u>Defined in</u>: </b>C:\Users\Administrator\Documents\Unified Functional Testing\senario1.qrs<br><b><u>Description</u>: </b><br><b><u>Post-recovery operation</u>: </b>Proceed to next step.<br><br><b><u>Activated by trigger</u>:</b><dd><u>Type</u>: Pop-up window<br><u>Contains the caption</u>: Login Failed<br><u>Contains the text</u>: OKIncorrect username or password.
Use: Username=john, Password=HP</dd><dt><br><b><u>The current test step details</u>:</b><dd><u>Object</u>: WpfEdit("agentName")<br><u>Method</u>: Set<br><u>Arguments</u>: join<br><u>Result</u>: SUCCEEDED</dd></dt></dl></div></SPAN>]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:16]]></Time>
<TimeTick>1678784356</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Login Failed]]></Obj>
<Details plainTxt="False" ><![CDATA[<SPAN class=text><div align=left><b><u>Hierarchical description</u>:</b> WpfWindow( devname := HPE MyFlight Sample Application, regexpwndtitle := HPE MyFlight Sample Application, wpftypename := window ).Dialog( is child window := 0, is owned window := -1, nativeclass := #32770, text := Login Failed )</div></SPAN>]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:16]]></Time>
<TimeTick>1678784356</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Button("OK").Click]]></Obj>
<Details plainTxt="False" ><![CDATA[<SPAN class=text><div align=left><b><u>Perform the method</u>:</b> Button("OK").Click<br><b>for detected object</b></div></SPAN>]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:16]]></Time>
<TimeTick>1678784356</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[WpfWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:17]]></Time>
<TimeTick>1678784357</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Dialog]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:17]]></Time>
<TimeTick>1678784357</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:17]]></Time>
<TimeTick>1678784357</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="19" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="18" >
<Disp><![CDATA[Dialog]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="17" >
<Disp><![CDATA[WpfWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="15" nType="Object operation" >
<Disp><![CDATA[Button("OK").Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Button("OK").Click]]></Obj>
<Details plainTxt="False" ><![CDATA[<SPAN class=text><div align=left><b><u>Perform the method</u>:</b> Button("OK").Click<br><b>for detected object</b></div></SPAN>]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:17]]></Time>
<TimeTick>1678784357</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Unspecified error
]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:18]]></Time>
<TimeTick>1678784358</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="21" status="Warning" >
<Disp><![CDATA[Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:24]]></Time>
<TimeTick>1678784364</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["640ff6762fd8f4d4f2a0"]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:24]]></Time>
<TimeTick>1678784364</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="43" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:25]]></Time>
<TimeTick>1678784365</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="45" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="42" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T18" iterID="1" >
<Action rID="T19">
<AName><![CDATA[Action1]]></AName>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:27]]></Time>
<TimeTick>1678784367</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:27]]></Time>
<TimeTick>1678784367</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="51" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="3" nRep="50" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-03-2023 - 14:29:26" eTime="14-03-2023 - 14:29:27" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="13" nRep="47" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T22">
<AName><![CDATA[Action2]]></AName>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:30]]></Time>
<TimeTick>1678784370</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["join"]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:30]]></Time>
<TimeTick>1678784370</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="60" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["640ff6762fd8f4d4f2a0"]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:31]]></Time>
<TimeTick>1678784371</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="62" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="59" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-03-2023 - 14:29:27" eTime="14-03-2023 - 14:29:31" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="13" nRep="53" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T26">
<AName><![CDATA[Action3]]></AName>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:33]]></Time>
<TimeTick>1678784373</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-03-2023 - 14:29:33]]></Time>
<TimeTick>1678784373</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="67" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="66" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-03-2023 - 14:29:31" eTime="14-03-2023 - 14:29:33" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="13" nRep="64" >
<Disp><![CDATA[Action3 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="12" nRep="46" status="Passed" >
<Disp><![CDATA[function test Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<NodeArgs eType="Replay" icon="8" nRep="20" status="Warning" nType="Object operation" >
<Disp><![CDATA[Button("OK").Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="14" status="Warning" nType="Detected object" >
<Disp><![CDATA[Login Failed]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="13" status="Warning" nType="PopUp Window" >
<Disp><![CDATA[s1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="11" status="Warning" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-03-2023 - 14:29:10" eTime="14-03-2023 - 14:29:33" passed="2" failed="0" warnings="3" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Warning" >
<Disp><![CDATA[Test function test Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>