<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="WINDOWS-UNR7VLH"><DocLocation><![CDATA[C:\Users\Administrator\Documents\Unified Functional Testing\day 3 lab 2]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[day 3 lab 2]]></DName>
<Res><![CDATA[Res12]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:16]]></Time>
<TimeTick>1678692496</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "http://demo.opencart.com/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "http://demo.opencart.com/",1]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:16]]></Time>
<TimeTick>1678692496</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Run "http://demo.opencart.com/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:38]]></Time>
<TimeTick>1678692518</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:38]]></Time>
<TimeTick>1678692518</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[top.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:38]]></Time>
<TimeTick>1678692518</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="16" Source="Action1" SourceLine="2" >
<Disp><![CDATA[top.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:39]]></Time>
<TimeTick>1678692519</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="19" Source="Action1" SourceLine="3" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Account Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:41]]></Time>
<TimeTick>1678692521</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ab@gmail.com"]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:41]]></Time>
<TimeTick>1678692521</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="25" Source="Action1" SourceLine="4" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1234"]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:41]]></Time>
<TimeTick>1678692521</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="28" Source="Action1" SourceLine="6" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:42]]></Time>
<TimeTick>1678692522</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="31" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="24" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Account Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13-03-2023 - 12:58:15" eTime="13-03-2023 - 12:58:42" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[day 3 lab 2 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T15" iterID="2" >
<Action rID="T16">
<AName><![CDATA[Action1]]></AName>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:43]]></Time>
<TimeTick>1678692523</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Run "http://demo.opencart.com/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "http://demo.opencart.com/",1]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:43]]></Time>
<TimeTick>1678692523</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="39" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Run "http://demo.opencart.com/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="38" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:44]]></Time>
<TimeTick>1678692524</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA["Your Store"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (2 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Your Store<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>title=Your Store<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openurl=https://demo.opencart.com<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=Your Store<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:44]]></Time>
<TimeTick>1678692524</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="42" Source="Action1" SourceLine="2" >
<Disp><![CDATA["Your Store"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:44]]></Time>
<TimeTick>1678692524</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[top.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:44]]></Time>
<TimeTick>1678692524</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="45" Source="Action1" SourceLine="2" >
<Disp><![CDATA[top.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:45]]></Time>
<TimeTick>1678692525</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="48" Source="Action1" SourceLine="3" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="44" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Account Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:46]]></Time>
<TimeTick>1678692526</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["abc@gmail.com"]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:46]]></Time>
<TimeTick>1678692526</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="52" Source="Action1" SourceLine="4" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["12w1"]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:46]]></Time>
<TimeTick>1678692526</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="55" Source="Action1" SourceLine="6" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:46]]></Time>
<TimeTick>1678692526</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="58" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="51" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Account Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="41" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13-03-2023 - 12:58:42" eTime="13-03-2023 - 12:58:46" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="35" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="34" status="Passed" >
<Disp><![CDATA[day 3 lab 2 Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T28" iterID="3" >
<Action rID="T29">
<AName><![CDATA[Action1]]></AName>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:47]]></Time>
<TimeTick>1678692527</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Run "http://demo.opencart.com/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "http://demo.opencart.com/",1]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:47]]></Time>
<TimeTick>1678692527</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="66" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Run "http://demo.opencart.com/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="65" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:54]]></Time>
<TimeTick>1678692534</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA["Your Store"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (3 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (3 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Your Store<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>title=Your Store<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openurl=https://demo.opencart.com<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=Your Store<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:54]]></Time>
<TimeTick>1678692534</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="69" Source="Action1" SourceLine="2" >
<Disp><![CDATA["Your Store"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:54]]></Time>
<TimeTick>1678692534</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[top.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:54]]></Time>
<TimeTick>1678692534</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="72" Source="Action1" SourceLine="2" >
<Disp><![CDATA[top.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:54]]></Time>
<TimeTick>1678692534</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="75" Source="Action1" SourceLine="3" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="71" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Account Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:56]]></Time>
<TimeTick>1678692536</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["123@gmail.com"]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:56]]></Time>
<TimeTick>1678692536</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="79" Source="Action1" SourceLine="4" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["8970"]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:56]]></Time>
<TimeTick>1678692536</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="82" Source="Action1" SourceLine="6" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:58:56]]></Time>
<TimeTick>1678692536</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="85" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="78" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Account Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="68" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13-03-2023 - 12:58:46" eTime="13-03-2023 - 12:58:56" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="62" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="61" status="Passed" >
<Disp><![CDATA[day 3 lab 2 Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="13-03-2023 - 12:58:10" eTime="13-03-2023 - 12:58:56" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test day 3 lab 2 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>